name: Build and Test
on: push

jobs:
  test:
    name: Test Backend Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "15.x"

      - name: Install and Test 🔧
        working-directory: ./server
        run: |
          npm ci
          npm run test
