name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Backend Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Create config.json 📝
        working-directory: ./server
        run: |
          config="${{ secrets.CONFIG }}"
          echo "$config" > config.json

      - uses: actions/setup-node@v3
        with:
          node-version: "15.x"

      - name: Install and Test 🔧
        working-directory: ./server
        run: |
          npm ci
          npm run test
